### ISSUE TITLE
Weird car behavior

### ISSUE THREAD

**Issue by mijanto** [0xCAFEDECAF/VanLiveConnect#3]
As device is connected, fake Nodemcu with CP2102 USB chip and ESP-12E, sometimes when key is in ACC position, all dash lights light up for about second, then they turn off like they should be, and while driving, left airbag light (not the one with air bag letters) lights up, and stays up for the rest of the ride (until engine is turned off). Also, sometimes dash backlight dims to about half I have it set (like from 81% to about 40%) while driving. Device is connected to VAN bus and also powered from radio connector. As it was more suitable for the case, I connected it to pin D6 on NodeMCU. I'm using SN65HVD230 transceiver. 

Data were displayed correctly, I really liked it (except the fuel consumption, 0.2l/100km :) ).

**Comment by 0xCAFEDECAF** [comment]
That sounds weird, indeed! The hardware (and software) are setup to only listen to the VAN bus, not write packets onto it.

Does the same issue arise when running the simple [packet dumper](https://github.com/0xCAFEDECAF/VanBus/tree/master/examples/VanBusDump)? And what happens when the CANL and CANH (radio pins 2 and 3) are disconnected?

> I really liked it (except the fuel consumption, 0.2l/100km :) ).

I'm afraid I don't understand...

**Comment by 0xCAFEDECAF** [comment]
If you have a "type C" LCD display (MFD), you could also consider connecting the CANL and CANH to pins 17 and pin 4 (respectively) of that MFD. See also this diagram showing the "minimal VAN bus network" with only head unit and MFD:

![Smallest VAN network](https://user-images.githubusercontent.com/31759302/187431278-4341194d-2f27-421e-bf0d-3705427ae11d.jpg)
