### ISSUE TITLE
How to change theme colors?

### ISSUE THREAD

**Issue by maquiano** [0xCAFEDECAF/VanLiveConnect#5]
Hi,
I did the project and works great but I'd like to personalize the interface colors. I tried to make some changes by my own but I don't know how exactly do it because of the different possibilities. Light theme, dark theme, dimmer, etc. I can't identify where are each of them.
Could you give me a little guide on how to do that?.
Thanks in advance.

**Comment by 0xCAFEDECAF** [comment]
Hi, you have to make the changes in [`function setColorTheme` in MFD.js.ino](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/31d1bab0a44f46833060d4c229bf7f20193e04da/VanLiveConnect/MFD.js.ino#L1727), in [`function setLuminosity` in MFD.js.ino](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/31d1bab0a44f46833060d4c229bf7f20193e04da/VanLiveConnect/MFD.js.ino#L1760), and in the [`:root` style in CarInfo.css.ino](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/31d1bab0a44f46833060d4c229bf7f20193e04da/VanLiveConnect/CarInfo.css.ino#L28).

**Comment by maquiano** [comment]
Thanks,
it works.

I have few questions.
How could I change the font?
How could I attach the Background image and make it visible?
Can you help me to fit info on my screen?
![1679750582278](https://user-images.githubusercontent.com/128356913/227719979-43c27c10-2a8a-40eb-a98b-c82207ac4088.jpg)

**Comment by 0xCAFEDECAF** [comment]
Nice! :smiley:

Background image is in the [`data` directory, here](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/main/VanLiveConnect/data/background.jpg). Ofc you can put your own image there.

You must upload it to your ESP's SPI Flash File System (SPIFFS), and have the ESP web server serve all content from that file system. Instructions how to do this are here: https://github.com/0xCAFEDECAF/VanLiveConnect/issues/4#issuecomment-1273033207 .

If the ESP web server is serving content from SPIFFS, the changes you made in [MFD.js.ino](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/main/VanLiveConnect/MFD.js.ino) must be copied into [MFD.js.gz](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/main/VanLiveConnect/data/MFD.js.gz). Note that .gz format and file extension is not required (just more efficient).

> Can you help me to fit info on my screen?

Your screen has slightly different aspect ratio. I will check the resizing code to take into account the screen height so that all is visible.

**Comment by 0xCAFEDECAF** [comment]
> Can you help me to fit info on my screen?

Latest commit now takes into account the screen height so that it always fits.

> How could I change the font?

You need to replace the .woff files ([DSEG14Classic-BoldItalic.woff](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/main/VanLiveConnect/data/DSEG14Classic-BoldItalic.woff), [DSEG7Classic-BoldItalic.woff](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/main/VanLiveConnect/data/DSEG7Classic-BoldItalic.woff), [DotsAllForNow.woff](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/main/VanLiveConnect/data/DotsAllForNow.woff) and [ArialRoundedMTbold.woff](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/main/VanLiveConnect/data/ArialRoundedMTbold.woff)), and update all references to them. This is a big task, since all UI elements are sized to fit.

**Comment by maquiano** [comment]
Thanks very much!,
Now the screen fits with the height. The font is a bit complicate to me and Its right as you create it.

The final results... by now!.
![vlc_014](https://user-images.githubusercontent.com/128356913/230595544-b32fa800-0c8a-42f0-b0b6-85d2bf848ac3.jpg)

**Comment by 0xCAFEDECAF** [comment]
That's cool! 😃 Thanks for sharing the results!

**Comment by 0xCAFEDECAF** [comment]
> How could I change the font?

The latest commit now uses the [PeugeotNew font](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/main/VanLiveConnect/data/PeugeotNewRegular.woff). The screen layout now looks much nicer 😃

**Comment by Edronax** [comment]
> Thanks, it works.
> 
> I have few questions. How could I change the font? How could I attach the Background image and make it visible? Can you help me to fit info on my screen? ![1679750582278](https://user-images.githubusercontent.com/128356913/227719979-43c27c10-2a8a-40eb-a98b-c82207ac4088.jpg)

oh wow what a fancy design! can you share your modifications ? what phone is this, looks goodfitting? Would also like to use it on my 406 coupe now that my display is broken

**Comment by 0xCAFEDECAF** [comment]
Thanks 😄 

> can you share your modifications 

Which modifications are you referring to?

**Comment by Edronax** [comment]
@0xCAFEDECAF the modification for the theme that it looks so similar to the original display. 
just ordered everything, will try it myself!

**Comment by 0xCAFEDECAF** [comment]
> will try it myself!

Nice! Keep us updated!

> the modification for the theme that it looks so similar to the original display

Ah you mean the "orange" color theme. I don't have it, it is done by @maquiano . @maquiano can you show us the modifications?

**Comment by maquiano** [comment]
Hi mates!,
Excuse me, I'm a bit busy this days. When I had time I will share my modified version.
Regards.

**Comment by 0xCAFEDECAF** [comment]
> Excuse me, I'm a bit busy this days. When I had time I will share my modified version.

No problem, take care!

**Comment by maquiano** [comment]
Sorry for the delay.
Here is my last modified VLC.
[VLC_maquiano_mod.zip](https://github.com/0xCAFEDECAF/VanLiveConnect/files/12266807/VLC_maquiano_mod.zip)

**Comment by 0xCAFEDECAF** [comment]
Thanks! Appreciated :smile:

**Comment by Edronax** [comment]
@maquiano
Thx, I would definitely like to try this. 

@0xCAFEDECAF 
I am still quite unused to the topic of ardunio and git. Have a problem where I hang something, should I open a new problem? Thank you!

**Comment by 0xCAFEDECAF** [comment]
@Edronax : best to have the web documents (html, css, js, ...) served from the SPI Flash File System (SPIFFS) by uncommenting the line `#define SERVE_FROM_SPIFFS` in the [`Config.h` file](https://github.com/0xCAFEDECAF/VanLiveConnect/blob/8f85f6f4a152c39f0642307f91c28f9065f24376/VanLiveConnect/Config.h#L169).

Also, you must apply all the patches as found in the [`Patches`](https://github.com/0xCAFEDECAF/VanLiveConnect/tree/main/VanLiveConnect/Patches) directory.
